---
abstract: 'Provide bash completion for Sub::Spec::CmdLine programs'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-BashComplete
requires:
  Data::Sah: 0
  File::Which: 0
  Log::Any: 0
  Sub::Spec: 1.0.2
  Sub::Spec::GetArgs::Argv: 0.02
  UUID::Random: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-BashComplete/
  repository: http://github.com/sharyanto/perl-Sub-Spec-BashComplete
version: 0.18
